apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-v6-discovery
  namespace: development
  labels:
    app: couchbase-v6
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8091
    targetPort: http
  - name: https
    port: 18091
    targetPort: https
  selector:
    app: couchbase-v6
---
### this pod level service will allow Couchbase-SDK to connect to Couchbase
### your APP should live in the same cluster with Couchbase
apiVersion: v1
kind: Service
metadata:
  name: couchbase-v6
  namespace: development
  labels:
    app: couchbase-v6
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8091
    targetPort: http
  - name: https
    port: 18091
    targetPort: https
  selector:
    app: couchbase-v6
---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-v6-secrets
  namespace: development
  labels:
    app: couchbase-v6
type: Opaque
data:
  couchbase-password: ""
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: couchbase-v6
  namespace: development
  labels:
    app: couchbase-v6
spec:
  selector:
    matchLabels:
      app: couchbase-v6
  maxUnavailable: 1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couchbase-v6
  namespace: development
  labels:
    app: couchbase-v6
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: "couchbase-v6"
  replicas: 2
  template:
    metadata:
      labels:
        app: couchbase-v6
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9119"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - couchbase-v6
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: ulimit
        image: busybox
        imagePullPolicy: Always
        command: ["sh", "-c", "ulimit -n 40960 && ulimit -c 100000000 && ulimit -l 100000000"] # Since unlimited is not supported as a value, it sets the core and memlock values to 100 GB.  
        securityContext:
          privileged: true
      containers:
      - name: couchbase-v6
        image: travix/travix/k8s-couchbase-6.0-community:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2
            memory: 4096Mi
          requests:
            cpu: 1
            memory: 4096Mi
        ports:
        - name: http
          containerPort: 8091
        - name: https
          containerPort: 18091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 8094
        - containerPort: 11209
        - containerPort: 11210
        - containerPort: 11211
        - containerPort: 4369
        - containerPort: 9998
        - containerPort: 9999
        - containerPort: 11207
        - containerPort: 11214
        - containerPort: 11215
        - containerPort: 9100
        - containerPort: 9101
        - containerPort: 9102
        - containerPort: 9103
        - containerPort: 9104
        - containerPort: 9105
        - containerPort: 18091
        - containerPort: 18092
        - containerPort: 18093
        - containerPort: 21100
        - containerPort: 21101
        - containerPort: 21299
        env:
        - name: "AUTOFAILOVER_TIMEOUT"
          value: "60"
        - name: "DISCOVERY_SERVICE"
          value: "couchbase-v6-0.couchbase-v6.development.svc.cluster.local"
        - name: "FTS_RAM_SIZE_MB"
          value: "256"
        - name: "INDEX_RAM_SIZE_MB"
          value: "256"
        - name: "USER"
          value: "Administrator"
        - name: "PASSWORD"
          valueFrom:
            secretKeyRef:
              name: couchbase-v6-secrets
              key: couchbase-password
        - name: "APP_NAME"
          value: "couchbase-v6"
        - name: "RAM_SIZE_MB"
          value: "2048"
        - name: "REBALANCE_ON_NODE_ADDITION"
          value: "1"
        - name: "SERVICES"
          value: "data,index,query,fts"
        livenessProbe:
          exec:
            command: ['sh', '-c', '/liveness.sh']
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command: ['sh', '-c', '/readiness.sh']
          initialDelaySeconds: 10
          failureThreshold: 1
          periodSeconds: 2
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', '/prestop.sh']
        volumeMounts:
        - name: couchbase-v6-data
          mountPath: /opt/couchbase/var
      - name: couchbase-v6-exporter
        image: travix/couchbase-exporter:GKE
        imagePullPolicy: Always
        env:
        - name: "COUCHBASE_HOST"
          value: "127.0.0.1"
        - name: "COUCHBASE_PORT"
          value: "8091"
        - name: "COUCHBASE_USERNAME"
          value: "Administrator"
        - name: "COUCHBASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: couchbase-v6-secrets
              key: couchbase-password
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9119
          initialDelaySeconds: 10
          timeoutSeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi
        ports:
        - name: metrics
          containerPort: 9119
  volumeClaimTemplates:
  - metadata:
      name: couchbase-v6-data
      namespace: development
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
